In [60]:
import pandas as pd
data = pd.read_csv('ratings.csv') #Сформировал таблицу из файла

In [62]:
data_rating = data[ data['rating'] == 5.0]  #Сформировал отдельную таблицу, где указаны только строки с оценкой 5
film = data_rating['movieId'].value_counts().head(1)
print('Фильм с ID', film.index.tolist(), 'имеет наибольшее количество оценок "5" - ', film.tolist())

Фильм с ID [318] имеет наибольшее количество оценок "5" -  [48762]

In [63]:
data = pd.read_csv('power.csv') #Сформировал таблицу из файла
data_filtred = data[ ((data['country'] == 'Lithuania') | (data['country'] == 'Latvia') | (data['country'] == 'Estonia')) &  
                    ((data['category'] == 4) | (data['category'] == 12) | (data['category'] == 21)) &
                   (data['quantity'] >= 0) & (data['year'] >= 2005) & (data['year'] <= 2010)]
data_filtred

          country  year  quantity  category
10617     Estonia  2008       1.0         4
10618     Estonia  2007       0.0         4
10619     Estonia  2006       0.0         4
10620     Estonia  2005       1.0         4
11156   Lithuania  2008       1.0         4
...           ...   ...       ...       ...
253982  Lithuania  2009      98.0        21
253983  Lithuania  2008      54.0        21
253984  Lithuania  2007      47.0        21
253985  Lithuania  2006      31.0        21
253986  Lithuania  2005       1.0        21

[408 rows x 4 columns]

In [58]:
"""
Не совсем понял задачу. Нужно ли все таблицы с сайта привести в вид, который ниже прописан?
"""
page_url = 'https://www.finanz.ru/valyuty/v-realnom-vremeni'
table_html = pd.read_html(page_url, encoding='utf-8')
table = table_html[1]
table.drop (axis = 0, index = [6, 11, 16, 21, 26, 31], inplace=True)
table.drop('Unnamed: 0', axis = 1, inplace=True)
table.drop('Спрос', axis = 1, inplace=True)
table

,Рубль,Предложение,Предыдущее закрытие,%,Абсолютное значение,Время
0,GBP/RUB,1040479,1039766,"0,07 %",00713,19:03:00
1,EUR/RUB,919818,920190,"-0,04 %",-00372,19:04:00
2,USD/RUB,761250,758565,"0,35 %",02685,19:04:00
3,JPY/RUB,07255,07238,"0,22 %",00016,19:04:00
4,CNY/RUB,117723,118014,"-0,25 %",-00291,19:03:00
5,CHF/RUB,850150,851790,"-0,19 %",-01640,19:04:00
7,EUR/USD,12081,12130,"-0,40 %",-00049,19:04:00
8,EUR/GBP,08842,08853,"-0,12 %",-00010,19:04:00
9,EUR/JPY,1268050,1271300,"-0,26 %",-03250,19:04:00
10,EUR/CHF,10819,10799,"0,18 %",00020,19:04:00
12,USD/EUR,08276,08244,"0,39 %",00032,19:04:00
13,USD/GBP,07318,07296,"0,31 %",00022,19:03:00
14,USD/JPY,1049450,1048050,"0,13 %",01400,19:04:00
15,USD/CHF,08956,08905,"0,57 %",00051,19:04:00
17,JPY/EUR (100:1),07900,07900,"0,25 %",00000,19:04:00
18,JPY/GBP,00070,00070,"0,16 %",00000,19:04:00
19,JPY/USD,00095,00095,"-0,15 %",00000,19:04:00
20,JPY/CHF (100:1),08500,08500,"0,45 %",00000,19:04:00
22,GBP/USD,13667,13705,"-0,28 %",-00039,19:04:00
23,GBP/JPY,1434224,1436494,"-0,16 %",-02270,19:03:00
24,GBP/EUR,11311,11298,"0,12 %",00013,19:04:00
25,GBP/CHF,12236,12202,"0,28 %",00034,19:04:00
27,GBP/CHF,12236,12202,"0,28 %",00034,19:04:00
28,EUR/CHF,10819,10799,"0,18 %",00020,19:04:00
29,JPY/CHF (100:1),08500,08500,"0,45 %",00000,19:04:00
30,USD/CHF,08956,08905,"0,57 %",00051,19:04:00
32,EUR/UAH,339019,341430,"-0,71 %",-02411,19:03:00
33,USD/UAH,280587,281475,"-0,32 %",-00888,19:03:00
34,CHF/UAH,313365,316068,"-0,86 %",-02703,19:03:00
35,GBP/UAH,383422,385822,"-0,62 %",-02401,19:03:00